test1/config/routes.rb
Rails.application.routes.draw do
  get 'test1/test12'

  get 'abcde/def'
  root 'abcde#def'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

test1/app/models/abcde.rb
class Abcde < ApplicationRecord
	validates :exampleInputEmail1 length:{maximum: 10, too_long: "ban da nhap email qua dai"}
end

test1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test1/app/controllers/abcde_controller.rb
class AbcdeController < ApplicationController
  def def
  end
end

test1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

test1/app/controllers/test1_controller.rb
class Test1Controller < ApplicationController
  def test12
  end
end

test1/app/helpers/abcde_helper.rb
module AbcdeHelper
	def maketle(title="")
		title + "Test App"
	end
end

test1/app/helpers/application_helper.rb
module ApplicationHelper
	
end

test1/app/helpers/test1_helper.rb
module Test1Helper
end

test1/app/views/abcde/def.html.erb
<% provide(:title,"Trang chu ") %> 

	<form>
	  <div class="form-group">
	    <label for="exampleInputEmail1">Email address</label>
	    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
	  </div>
	  <div class="checkbox">
	    <label>
	      <input type="checkbox"> Check me out
	    </label>
	  </div>
	  <%= link_to "Submit", test1_test12_path, class: 'btn btn-default'%>
	</form>

test1/app/views/layouts/_nav.html.erb
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">	 
	    <ul class="nav navbar-nav"  style="font-size:20px;">
	      <li><a href="#"><span class="glyphicon glyphicon-home"></span> </a></li>
	      <li><a href="#">HTML</a></li>
	      <li><a href="#">CSS</a></li>
	      <li><a href="#">JAVASCRIPT</a></li>
	      <li><a href="#">SQL</a></li>
	      <li><a href="#">PHP</a></li>
	      <li><a href="#">BOOTSTRAP</a></li>
	      <li><a href="#">JQUERY</a></li>
	      <li >
    			<a data-toggle="dropdown" href="#">
    				MORE
    				<span class="caret"></span>
  				</a>
	        <ul class="dropdown-menu" style ="font-size:20px;"  >			          
	          <li>
          		<a data-toggle="dropdown-menu-2" href="#">
          			HTML and CSS
	        			<span class="caret"></span>
        			</a>
			        <ul class="dropdown-menu-2" style ="font-size:20px;">
          			<li> <a href="#">Learn HTML </a> </li>
<!-- 		          			<li> <a href="#">Learn CSS </a> </li>
          			<li> <a href="#">Learn W3.CSS </a> </li>
          			<li> <a href="#">Learn Colors </a> </li>
          			<li> <a href="#">Learn Bootstrap </a> </li>
          			<li> <a href="#">Learn Graphics </a> </li>
          			<li> <a href="#">Learn Icons </a> </li>
          			<li> <a href="#">Learn How To </a> </li> -->
          		</ul>
	          </li>

	          <li><a href="#">Server Side</a></li>
	        </ul>
	      </li>	    
	      <li><a href="#">REFERENCE</a></li>
	      <li><a href="#">EXAMPLE</a></li>
	      <li><a href="#"><span class="glyphicon glyphicon-transfer"></a></li>
	      <li><a href="#"><span class="glyphicon glyphicon-search"></a></li>
	    </ul>
	    
	  </div>
	</nav>

test1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= maketle(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/nav" %>
  	<div class ="container">
  		<%= yield %>
  	</div>
  </body>
</html>

test1/app/views/test1/test12.html.erb
		<% provide(:title,"Test1 ") %> 
		<%= link_to "Submit", abcde_def_path, class: 'btn btn-default'%>